name: arcane
services:
  arcane:
    cpu_shares: 90
    command: []
    container_name: arcane
    deploy:
      resources:
        limits:
          memory: 16656248832
        reservations:
          devices: []
    environment:
      - APP_URL=http://192.168.68.xx:xxxx
      - ENCRYPTION_KEY=123455
      - JWT_SECRET=12345
      - PGID=1000
      - PUID=1000
    image: ghcr.io/getarcaneapp/arcane:latest
    labels:
      icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/arcane.png
    ports:
      - target: 3552
        published: "4040"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /DATA/AppData/arcane/data
        target: /app/data
      - type: bind
        source: /DATA/AppData/arcane/projects
        target: /app/data/projects
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
x-casaos:
  architectures:
    - amd64
    - arm64
  author: self
  category: Charlie
  description:
    en_us: Arcane is a fast, modern Docker Compose UI that completely outclasses
      Portainer and Dockge with auto-discovery and an incredibly clean mobile
      layout.
  developer: getarcaneapp
  hostname: ""
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/arcane.png
  index: /
  is_uncontrolled: false
  main: arcane
  port_map: "4040"
  scheme: http
  store_app_id: arcane
  tagline:
    en_us: The future of Docker container management.
  title:
    custom: ""
    en_us: Arcane
