name: searxng
services:
  # Search Engine
  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    environment:
      - SEARXNG_BASE_URL=http://192.168.1.XX:3025/ # Change to your ZimaOS IP
    ports:
      - target: 8080
        published: "3025"
        protocol: tcp
    volumes:
      - /DATA/AppData/searxng:/etc/searxng:rw
    depends_on:
      - redis
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    restart: unless-stopped
    x-casaos:
      ports:
        - container: "8080"
          description:
            en_us: "Web Interface"
      volumes:
        - container: /etc/searxng
          description:
            en_us: "Configuration"

  # Cache Database
  redis:
    container_name: searxng-redis
    image: redis:alpine
    command: redis-server --save "" --appendonly no
    restart: unless-stopped
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID

x-casaos:
  architectures:
    - amd64
    - arm64
  main: searxng
  author: SearxNG Team
  category: Charlie
  description:
    en_us: "SearXNG is a free internet metasearch engine which aggregates results from more than 70 search services."
  developer: "SearXNG"
  icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/searxng.png"
  tagline:
    en_us: "Privacy-respecting search engine."
  title:
    en_us: "SearXNG"
  port_map: "3025"
  scheme: http
