name: libretranslate
services:
  libretranslate:
    container_name: libretranslate
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    ports:
      - 4020:5000
    environment:
      - LT_LOAD_ONLY=en,es,fr,de
      - LT_THREADS=4
      - LT_DEFAULT_SOURCE=en
      - LT_DEFAULT_TARGET=en-GB
    volumes:
      - /DATA/AppData/$AppID/data:/home/libretranslate/.local

x-casaos:
  architectures:
    - amd64
    - arm64
  main: libretranslate
  title:
    en_us: LibreTranslate
  tagline:
    en_us: Free and Open Source Machine Translation API.
  description:
    en_us: LibreTranslate is a free and open-source machine translation API, entirely self-hosted. It is easy to set up and provides high-quality translations across various languages.
  developer: LibreTranslate
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/libretranslate.png
  category: Charlie
  port_map: "4020"
