name: commafeed
services:
  commafeed:
    environment:
      - PUID=0
      - PGID=0
      - QUARKUS_HTTP_AUTH_SESSION_EXPIRATION_KEY=ReplaceWithLongRandomString # change this
    image: athou/commafeed:latest-h2
    deploy:
      resources:
        reservations:
          memory: 256M
    network_mode: bridge
    ports:
      - target: 8082
        published: "8082"
        protocol: tcp
    privileged: true
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/commafeed/data
        target: /commafeed/data
    x-casaos:
      ports:
        - container: "8082"
          description:
            en_us: "Web Interface"
      volumes:
        - container: /commafeed/data
          description:
            en_us: "Database and Application Data"
    container_name: commafeed
x-casaos:
  architectures:
    - amd64
    - arm64
  main: commafeed
  author: CasaOS Team
  category: Charlie
  description:
    en_us: A Google Reader inspired self-hosted RSS reader. Lightweight, fast, and privacy-focused.
  developer: Athou
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/commafeed.png
  tagline:
    en_us: Self-hosted RSS feed reader.
  title:
    en_us: CommaFeed
  port_map: "8082"
